{
 "title": "Upstream URL Checker",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Upstream Response Time ms P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sample_external_url_response_ms_bucket[5m])) by (le, url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Upstream Average Response Time ms ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (url) (rate(sample_external_url_response_ms_sum[5m]) / rate(sample_external_url_response_ms_count[5m]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Upstream URL Status Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (url) (sample_external_url_up)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Upstream URL Status History",
   "type": "timeseries",
   "description": "Gauge metric reporting the status of an upstream url, 1 == 200, 0 == non-200 status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by (url) (sample_external_url_up)"
    }
   ]
  }
 ]
}