--- 
apiVersion: v1
kind: Namespace
metadata:
  name: url-checker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-checker
  namespace: url-checker
  labels:
    app: url-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-checker
  template:
    metadata:
      labels:
        app: url-checker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
    spec:
      containers:
      - name: url-checker
        image: url-checker:1.0
        imagePullPolicy: IfNotPresent
        args:
          - "-upstream-urls"
          - "https://httpstat.us/200,https://httpstat.us/503"
        ports:
        - containerPort: 9090
          name: metrics
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9090
          initialDelaySeconds: 2
          periodSeconds: 3



